Repository CMU-17313Q/nodebb-f24-codehers, pull requests merged in 2024-10, with the labels that each got.

#56 Add Automated Tests for Bug/Feedback Form and Bug Archive Page - User Story 2
  test/bug-archive.js
  test/bug-form.js
Labels: UserStory2

#47 Testing anonymous posting feature for Topics and Posts-User Story 3
  .gitignore
  node_modules/nodebb-plugin-composer-default/.eslintrc
  node_modules/nodebb-plugin-composer-default/.gitattributes
  node_modules/nodebb-plugin-composer-default/.jshintrc
  node_modules/nodebb-plugin-composer-default/LICENSE
  node_modules/nodebb-plugin-composer-default/README.md
  node_modules/nodebb-plugin-composer-default/controllers.js
  node_modules/nodebb-plugin-composer-default/library.js
  node_modules/nodebb-plugin-composer-default/package.json
  node_modules/nodebb-plugin-composer-default/plugin.json
  node_modules/nodebb-plugin-composer-default/screenshots/desktop.png
  node_modules/nodebb-plugin-composer-default/screenshots/mobile.png
  node_modules/nodebb-plugin-composer-default/static/lib/.eslintrc
  node_modules/nodebb-plugin-composer-default/static/lib/admin.js
  node_modules/nodebb-plugin-composer-default/static/lib/client.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/autocomplete.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/categoryList.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/controls.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/drafts.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/formatting.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/post-queue.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/preview.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/resize.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/scheduler.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/tags.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/uploads.js
  node_modules/nodebb-plugin-composer-default/static/scss/composer.scss
  node_modules/nodebb-plugin-composer-default/static/scss/page-compose.scss
  node_modules/nodebb-plugin-composer-default/static/scss/textcomplete.scss
  node_modules/nodebb-plugin-composer-default/static/scss/zen-mode.scss
  node_modules/nodebb-plugin-composer-default/static/templates/admin/plugins/composer-default.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/compose.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/modals/topic-scheduler.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-formatting.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-tags.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-write-preview.tpl
  node_modules/nodebb-plugin-composer-default/websockets.js
  node_modules/nodebb-theme-harmony/templates/category.tpl
  public/language/en-GB/topic.json
  public/openapi/components/schemas/PostObject.yaml
  public/openapi/components/schemas/TopicObject.yaml
  src/posts/create.js
  src/topics/create.js
  src/topics/fork.js
  src/topics/index.js
  src/topics/posts.js
  test/api.js
  test/posts.js
  test/topics.js
Labels: documentation, low effort, UserStory3

#34 Working on the backend for the functionality of searching through documents - User Story 1
  dump.rdb
  node_modules/nodebb-theme-harmony/templates/category.tpl
  node_modules/nodebb-theme-harmony/templates/partials/posts_list.tpl
  node_modules/nodebb-theme-harmony/templates/users.tpl
  public/src/client/categories.js
  public/src/client/category.js
  public/src/client/groups/list.js
  public/src/client/topic.js
  public/src/client/users.js
  public/src/modules/categorySearch.js
  src/api/categories.js
  src/api/posts.js
  src/api/topics.js
  src/api/users.js
  src/batch.js
  src/categories/topics.js
  src/controllers/categories.js
  src/controllers/topics.js
  src/controllers/users.js
  src/controllers/write/posts.js
  src/groups/index.js
  src/groups/search.js
  src/routes/api.js
  src/routes/write/posts.js
  src/socket.io/admin/rooms.js
  src/topics/create.js
  src/topics/events.js
  test/api.js
Labels: high effort, back-end
